version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  koa:
    image: node:8
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3030:3030
    depends_on:
      - mongo
    command: yarn start-koa
